### ISSUE TITLE
Could you provide the weights trained on imagenet?

### ISSUE THREAD

**Issue by 2yjia** [pkumivision/FFC#1]
Hi，Could you provide the weights trained on imagenet?Thank you !

**Comment by phongnhhn92** [comment]
Hello, I am also interested in using the pretrained model. Please upload it !

**Comment by 1820366459** [comment]
[FFC-ResNet-50](https://drive.google.com/file/d/1bAbCJR7lNfBbF2gdREcrsjHqa8HIgI3N/view?usp=sharing) with ratio=0.25
[FFC-ResNet-50 (+LFU)](https://drive.google.com/file/d/1egTVmTr3l2pS1lPeplRinwp1b5YjVMOU/view?usp=sharing) with ratio=0.25
Note: The models provided here are trained on MXNet’s recordIO files, so the performance will drop significantly while evaluated on JPEG images. But they can be used as good training initalization for other tasks.

**Comment by hzphzp** [comment]
> [FFC-ResNet-50](https://drive.google.com/file/d/1bAbCJR7lNfBbF2gdREcrsjHqa8HIgI3N/view?usp=sharing) with ratio=0.25 [FFC-ResNet-50 (+LFU)](https://drive.google.com/file/d/1egTVmTr3l2pS1lPeplRinwp1b5YjVMOU/view?usp=sharing) with ratio=0.25 Note: The models provided here are trained on MXNet’s recordIO files, so the performance will drop significantly while evaluated on JPEG images. But they can be used as good training initalization for other tasks.

Hi~ Thank you for sharing.
But the given pretrain model and code seem to match on the code architecture. Can you please check it out?  
And could you please approve my applying for downloading FFC-ResNet-50 (+LFU)?

**Comment by 1820366459** [comment]
> > [FFC-ResNet-50](https://drive.google.com/file/d/1bAbCJR7lNfBbF2gdREcrsjHqa8HIgI3N/view?usp=sharing) with ratio=0.25 [FFC-ResNet-50 (+LFU)](https://drive.google.com/file/d/1egTVmTr3l2pS1lPeplRinwp1b5YjVMOU/view?usp=sharing) with ratio=0.25 Note: The models provided here are trained on MXNet’s recordIO files, so the performance will drop significantly while evaluated on JPEG images. But they can be used as good training initalization for other tasks.
> 
> Hi~ Thank you for sharing. But the given pretrain model and code seem to match on the code architecture. Can you please check it out? And could you please approve my applying for downloading FFC-ResNet-50 (+LFU)?

Try again?
