### ISSUE TITLE
Input channel mismatch

### ISSUE THREAD

**Issue by huameinan219** [pkumivision/FFC#12]
Using ffc() to directly replace nn.Conv2d() will report an error:
`RuntimeError: Given groups=1, weight of size [5, 3, 3, 3], expected input[3, 6, 64, 64] to have 3 channels, but got 6 channels instead`

**Comment by ZeliangM** [comment]
> 
May be the input channels and output channels should be same, but I meet the other error!

**Comment by ZeliangM** [comment]
> 

I meet the same problem if ration_gin is not zero!

**Comment by huameinan219** [comment]
> > 
> 
> I meet the same problem if ration_gin is not zero!
我也是遇到的这个问题，然后我参考了文件ffc_resnet.py中实现BisicBlock类的做法，我使用三层ffc来代替原来的卷积层。
`self.ffclayers = nn.Sequential(FFC(channels, channels, 3, 0, 0.75, stride=1, padding=1,
                dilation=1, groups=1, bias=False, enable_lfu=False),
            FFC(channels, channels, 3, 0.75, 0.75, stride=1, padding=1,
                dilation=1, groups=1, bias=False, enable_lfu=False),
            FFC(channels, self.out_channel, 3, 0.75, 0, stride=1, padding=1,
                dilation=1, groups=1, bias=False, enable_lfu=False),
            ConcatTupleLayer(),),`
这里的ConcatTupleLayer()参考的[https://github.com/saic-mdal/lama](url)
`class ConcatTupleLayer(nn.Module):
    def forward(self, x):
        assert isinstance(x, tuple)
        x_l, x_g = x
        assert torch.is_tensor(x_l) or torch.is_tensor(x_g)
        if not torch.is_tensor(x_g):
            return x_l
        return torch.cat(x, dim=1)`

我在一个人脸修复任务中的开头的卷积层应用了快速傅里叶卷积，效果好像还彳亍。

**Comment by huameinan219** [comment]
> > 
> 
> I meet the same problem if ration_gin is not zero!

I meet the same problem if ration_gin is not zero!
我也是遇到的这个问题，然后我参考了文件ffc_resnet.py中实现BisicBlock类的做法，我使用三层ffc来代替原来的卷积层。
`self.ffclayers = nn.Sequential(FFC(channels, channels, 3, 0, 0.75, stride=1, padding=1,
                                                   dilation=1, groups=1, bias=False, enable_lfu=False),
                                                 FFC(channels, channels, 3, 0.75, 0.75, stride=1, padding=1,
                dilation=1, groups=1, bias=False, enable_lfu=False),
            FFC(channels, self.out_channel, 3, 0.75, 0, stride=1, padding=1,
                dilation=1, groups=1, bias=False, enable_lfu=False),
            ConcatTupleLayer(),)`
这里的ConcatTupleLayer()参考的 [https://github.com/saic-mdal/lama](url)

`class ConcatTupleLayer(nn.Module):
    def forward(self, x):
        assert isinstance(x, tuple)
        x_l, x_g = x
        assert torch.is_tensor(x_l) or torch.is_tensor(x_g)
        if not torch.is_tensor(x_g):
            return x_l
        return torch.cat(x, dim=1)`
class ConcatTupleLayer(nn.Module): def forward(self, x): assert isinstance(x, tuple) x_l, x_g = x assert torch.is_tensor(x_l) or torch.is_tensor(x_g) if not torch.is_tensor(x_g): return x_l return torch.cat(x, dim=1)

我在一个人脸修复任务中的开头的卷积层应用了快速傅里叶卷积，效果好像还彳亍。

**Comment by ZeliangM** [comment]
> > > 
> > 
> > 
> > I meet the same problem if ration_gin is not zero!
> 
> I meet the same problem if ration_gin is not zero! 我也是遇到的这个问题，然后我参考了文件ffc_resnet.py中实现BisicBlock类的做法，我使用三层ffc来代替原来的卷积层。 `self.ffclayers = nn.Sequential(FFC(channels, channels, 3, 0, 0.75, stride=1, padding=1, dilation=1, groups=1, bias=False, enable_lfu=False), FFC(channels, channels, 3, 0.75, 0.75, stride=1, padding=1, dilation=1, groups=1, bias=False, enable_lfu=False), FFC(channels, self.out_channel, 3, 0.75, 0, stride=1, padding=1, dilation=1, groups=1, bias=False, enable_lfu=False), ConcatTupleLayer(),)` 这里的ConcatTupleLayer()参考的 [https://github.com/saic-mdal/lama](url)
> 
> `class ConcatTupleLayer(nn.Module): def forward(self, x): assert isinstance(x, tuple) x_l, x_g = x assert torch.is_tensor(x_l) or torch.is_tensor(x_g) if not torch.is_tensor(x_g): return x_l return torch.cat(x, dim=1)` class ConcatTupleLayer(nn.Module): def forward(self, x): assert isinstance(x, tuple) x_l, x_g = x assert torch.is_tensor(x_l) or torch.is_tensor(x_g) if not torch.is_tensor(x_g): return x_l return torch.cat(x, dim=1)
> 
> 我在一个人脸修复任务中的开头的卷积层应用了快速傅里叶卷积，效果好像还彳亍。

感谢您耐心回复，对我解决bug很有帮助。希望未来能有机会和您进一步交流。
