### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by cvejarano** [pkumivision/FFC#9]
Hi. First of all, thanks a lot for contributing your work to the community.
I noticed that this repo does't include a license file, so it's difficult to know the conditions for rightful use of it. Could you confirm under what conditions can your code be used and preferrably add a license file?

**Comment by 1820366459** [comment]
https://github.com/pkumivision/FFC/blob/main/LICENSE

**Comment by cvejarano** [comment]
Thanks a lot!
